## Configurações do Banco de Dados
# Configurações do JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

# Configurações do Swagger / OpenAPI
springdoc.cache.disabled=true

# Logs de Segurança (Opcional, útil para debug)
# logging.level.org.springframework.security=DEBUG