# Configuração do Banco de Dados (Postgres no Docker)
spring.datasource.url=jdbc:postgresql://db:5432/racha_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false

spring.jpa.hibernate.ddl-auto=validate
