# --- BANCO DE DADOS (H2) ---
spring.datasource.url=jdbc:h2:file:./data/racha_local_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# --- CLOUDFLARE R2 (Configuração Fixa para Teste Local) ---
spring.cloud.aws.region.static=auto

# Nome do Bucket
spring.cloud.aws.s3.bucket=${R2_BUCKET_NAME}

# URL Pública do Bucket
spring.storage.public-url=${R2_BUCKET_URL}

# Configuração de Tamanho do Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Seu Endpoint R2
spring.cloud.aws.s3.endpoint=${R2_ENDPOINT}

# Credenciais de Acesso
spring.cloud.aws.credentials.access-key=${R2_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${R2_SECRET_KEY}
