spring.application.name=racha_api

# Segurança (Tokens e OAuth)
api.security.token.secret=${JWT_SECRET}

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_ID_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# --- UPLOAD DE ARQUIVOS (Para as imagens) ---
# Permite arquivos até 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- CLOUDFLARE R2 CONFIG ---

# O Endpoint que você copiou do painel (SEM o nome do bucket no final)
spring.cloud.aws.s3.endpoint=https://748ee512f0355b3291133b289f6d74b6.r2.cloudflarestorage.com

# Região (O R2 ignora, mas a lib Java exige. Use 'auto' ou 'us-east-1')
spring.cloud.aws.region.static=auto

spring.cloud.aws.credentials.access-key=${R2_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${R2_SECRET_KEY}

# Nome do bucket que você criou
spring.cloud.aws.s3.bucket=racha-api-images

# URL pública para exibir as imagens (aquela do passo 1.4)
spring.storage.public-url=https://pub-ebd6cb94f7c8482bb69febdde6bb215f.r2.dev