spring.application.name=racha_api


## Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://db:5432/racha_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# Configurações do JPA
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

## Configurações de Segurança
api.security.token.secret=${JWT_SECRET}

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_ID_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Logs de Segurança (Opcional, útil para debug)
# logging.level.org.springframework.security=DEBUG
