# Configurações do Banco de Dados (H2 em arquivo local para persistir dados entre reinicios do VS Code)
spring.datasource.url=jdbc:h2:file:./data/racha_local_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Em DEV usamos update para não perder dados, ou create-drop para limpar sempre
spring.jpa.hibernate.ddl-auto=update

# Habilitar console do H2 (acessível em /h2-console)
spring.h2.console.enabled=true